dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: UpvaheGIm383HLqcYQTDAFdKqbkNsXjZ02KC1MakWYfa84+Neu8Uu4n9nxHshGFnUkuJear/eyU8/y4QEP4AkuUVDA+pm2nqBlw4JUXxiTMtj+rZY5rfxnqhrCtMPlxW2JCi98Kv5Sw/OUxStDQV6eNxmwynvecQnSuAJdadzhXBkxCLlC2PWO7KzuH5UEgqfhiSvj7VrmwE00m3bz8F7RerMUIDDoIHRkNKVaDLn5j8RjQVRuOXOByK9gIHQTl4O+dTTq1d8qz5R0vjDYubkQYRvMiprMmI9aHSRmcjxWu0W7bJDTL0o+dhasThxquSpOZp8+2fjJhSWZet/9k4w1Eud21ZYJVm8Fpb9ytA1D3/UNND9yNzE2qHg2lBX7YtK3lC1GtO5Bh4mKKPjGz4BoysmyzAQkilFBbGrwIEN1fhcaDszG3689uPDbT7jmfNrjhU94L2K1zj+lXvcBDzGwC0r8K4dP/WVlTnHvD5e9vYZVrXSI1HiWTncbKUkLMQ4ouN7xWuj06qXFjV2V25hsAX5T81jOSDBButVYDkU9SyuC3wcJ0SAQWm1XTlZR8sy0Jq5/Bb43mbiJ4FmyPODJ6KERJmm2/fQhr9UhjrMoM0jPB+RS3DqSx/MSzprFeKuOj+Jy70cqh2DkehfzFAWYWc/5qQzlgjDljWgbTkWN4=
  - secure: YIq7FW5UY6b7actdf43Pp95NvSlYc4sR08k4s7ClTPUy/P2ODyvqu0BplA2xOaIxZZPaK1VNU34YxUchVU/mll0qpURZ0HcA9xWzJxoqYFh/aEmTX24110lueCW0zmcpo05BE1gAVZ5Re+njmoJFVgsCo8AMrKIXBLkYNloyL1DnbRY9YR5dq4wbl7nMpPypIw78Np2Wol6E/YTmvlfEcgCsH2vISpZxnxxQkOm+AN5Kw55XJIfYPS1125bbarwvA8xuoE6BswWP8yrptmBR8A66yUrRPUEPgD6m5wZbS99XovMAjUEqGXv1wMlgGJwoJ3U9kAHJ5nJHxDZccN5bRfhMCrzIo06SbZCWB0yuxHSFcHQzX8KOFAvZRMzWl+JdibtgtgOXx8mO0rSuv4eo6SKpSY3QULCtObp3AMMiw8uoaKMGd66Dq65TKQRDNyFIUbT765JFE0IsuA92M97c5qSWbBkuO9JMd8VwneIjiywVIIbCwSWFWwlICU9VE2BwCFE27LthKGzuOW+bniCIa/BJ9/tdF7Dr9D0adVBLMIBPGnphsb/rmvAhU6G+Q7QrsHi8MhexTwtCmgtnV24FejsfLxJdMcjUs5OmFKbXVD3FNygvlPBlLlgIELbGRP1d1PdgheFpVIipbhMd5XXjXujwg3P8YFCl45V5FzUsvbU=
  - secure: BLJcH38/dc01SZnOYXe5SY+qc1qe4IC3sUbcXG3oIsdN1hbxBP08DMoWoReAkyt02QESuhj20+3ES4UDuZhD22c/9gkvpypk2OEGhJaD8ZVnqpFzbWEUpDPJAKUjTvxovvMuZrADuKMNcNY9qHLreYfEoY4NdiZBjrTOAKjx4KXx2k0I2GBrtR5YgSByvCsO++5vrzLggLaMMG9J4wUPK6O0/Pd715Sy2bWZwd5iM8KXyR9ttfhV6bmkiKk5kLM516RKPmgJtWQHEM6a1hceLbBUq3Lot99jHswRneVMe/pakJA59v3CmYubS2gLHrximYc49Z9FJZEnG+b2U/HJWQtbBAf9qza9RMORQNDPwXrRIJPzJIiUGJjCGtkKTHiJ8zRTGVOKQ4ZLYZv32kR0Txk2tS9i64vAz/Zdcignh//O0+hmaDiF2oVq5dWwtro5pXTaS+aUMCuwhrGVSerJ6XgY0xmE5gwEy2RFGj3dgGLiQfXHQpVfHvawNobr5JX5xLj2czbA3iRGRHTwJc2nDEDTOyMpk4CXBclzYPraMIzO3wK//vxk1JRYydzf7tRJK8KasUVBHFt5I24fPdrTL0ypHnM9X/ZxuVlAxGR6coZXSyDGJNVBTY3gpVYvY0PLupibguBCfFqwl9QX346VxMpR9itCL+oTxGUeKXwAd10=
install:
- nvm install 6.9.2
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
